const defaultProjects = [
  { title: 'ContextIQ', stack: 'React · Node.js · OpenAI API · LangChain · Pinecone · Stripe', description: 'A multi-tenant SaaS platform for custom RAG chatbots. Businesses can upload PDFs or URLs and get grounded, contextual answers with analytics and usage-based billing.', url: 'https://github.com/SamarthSharma11' },
  { title: 'SnapDeploy', stack: 'React · Node.js · GPT-4 API · WebContainers · Socket.io', description: 'A browser IDE that turns a plain-English prompt into a working app in seconds, streaming generated code live and applying follow-up requests as targeted diffs.', url: 'https://github.com/SamarthSharma11' },
  { title: 'DevPilot', stack: 'Python · FastAPI · LangChain · GitHub API · Docker · Redis', description: 'An autonomous PR-review agent that analyzes diffs, runs tests in a sandbox, and makes focused suggestions to help engineering teams move faster.', url: 'https://github.com/SamarthSharma11' }
];
const getProjects = () => JSON.parse(localStorage.getItem('samarth-projects') || 'null') || defaultProjects;
const saveProjects = (projects) => localStorage.setItem('samarth-projects', JSON.stringify(projects));
function renderProjects() { const projects = getProjects(); document.getElementById('projectGrid').innerHTML = projects.map((p, i) => `<article class="project"><span class="project-number">0${i + 1} / ${String(projects.length).padStart(2, '0')}</span><h3>${p.title}</h3><p class="project-stack">${p.stack}</p><p>${p.description}</p><a href="${p.url || '#'}" target="_blank" rel="noreferrer">View project <span>↗</span></a></article>`).join(''); document.getElementById('projectCount').textContent = `${String(projects.length).padStart(2, '0')} projects`; document.getElementById('adminProjectCount').textContent = String(projects.length).padStart(2, '0'); }
const panel = document.getElementById('adminPanel'), backdrop = document.getElementById('backdrop');
const setPanel = (open) => { panel.classList.toggle('open', open); backdrop.classList.toggle('open', open); panel.setAttribute('aria-hidden', String(!open)); };
document.getElementById('openAdmin').onclick = () => setPanel(true); document.getElementById('closeAdmin').onclick = () => setPanel(false); backdrop.onclick = () => setPanel(false);
document.getElementById('loginAdmin').onclick = () => { if (document.getElementById('adminCode').value === 'demo') { document.getElementById('adminLogin').hidden = true; document.getElementById('adminContent').hidden = false; } else { document.getElementById('adminCode').setCustomValidity('Try the demo access code.'); document.getElementById('adminCode').reportValidity(); } };
document.getElementById('projectForm').onsubmit = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); const projects = getProjects(); projects.push(data); saveProjects(projects); renderProjects(); event.target.reset(); };
document.getElementById('resetProjects').onclick = () => { localStorage.removeItem('samarth-projects'); renderProjects(); };
document.getElementById('contactForm').onsubmit = (event) => { event.preventDefault(); const messages = JSON.parse(localStorage.getItem('samarth-messages') || '[]'); messages.push({ ...Object.fromEntries(new FormData(event.target)), date: new Date().toISOString() }); localStorage.setItem('samarth-messages', JSON.stringify(messages)); document.getElementById('messageCount').textContent = String(messages.length).padStart(2, '0'); event.target.reset(); document.getElementById('formNote').textContent = 'Thanks — your message has been recorded.'; };
document.getElementById('messageCount').textContent = String(JSON.parse(localStorage.getItem('samarth-messages') || '[]').length).padStart(2, '0'); document.getElementById('year').textContent = new Date().getFullYear(); renderProjects();
